# Java Properties
target_java_version=21

# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.vfs.watch=true

# Minecraft Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loom_version=1.9-SNAPSHOT
loom.platform=neoforge
neoforge_version=21.1.209

# Mod Properties
mod_version=2.2.1+1.21.1-neoforge
maven_group=thomilist
archives_base_name=dimensional-inventories

# Dependencies
gson_version=2.13.2
apache_commons_io_version=2.21.0
curios_version=9.5.1+1.21.1

# Data pack format
data_pack_format=48
